/* hds-bypass: ops-internal widget. Inline styles intentional for standalone ops surface. */

/**
 * SecurityPostureWidget
 *
 * Renders a security posture summary card on the /ops dashboard.
 * All data comes from src/app/data/security-posture.json — a build-time
 * JSON sidecar generated by `pnpm audit:sidecar` (scripts/generate-security-posture.mjs).
 *
 * Data sources (all resolved at build time, never at runtime):
 *   - pnpm audit --json   → open finding counts
 *   - docs/security/audit-log.md  → last entry date
 *   - docs/security/agent-audit-log.jsonl → last run timestamp + outcome
 *
 * No hardcoded values. If the sidecar is missing or any field is null,
 * the widget renders an explicit "not yet run" state per field.
 */

import React from 'react';
import type { CSSProperties } from 'react';
import { Card, Badge, Stack, Field } from '@hirobius/design-system';
import hds from '@hirobius/design-system/tokens';
import postureRaw from '../../data/security-posture.json';

// ── Types ─────────────────────────────────────────────────────────────────────

interface AuditCounts {
  critical: number | null;
  high: number | null;
  moderate: number | null;
  low: number | null;
  total: number | null;
  lastRunDate: string | null;
}

interface SecurityPosture {
  generatedAt: string;
  audit: AuditCounts;
  auditLog: { lastEntryDate: string | null; grade: string | null };
  agentLog: { lastTimestamp: string | null; lastUnitId: string | null; lastOutcome: string | null };
}

// Vite eagerly resolves JSON imports — cast is safe here.
const posture = postureRaw as SecurityPosture;

// ── Helpers ───────────────────────────────────────────────────────────────────

type BadgeTone = 'neutral' | 'info' | 'success' | 'danger' | 'warning';
function gradeTone(grade: string | null): BadgeTone {
  if (!grade) return 'neutral';
  if (grade === 'A') return 'success';
  if (grade === 'B' || grade === 'C') return 'warning';
  return 'danger'; // F
}

// CardTone-compatible (matches Card.Metric tone prop)
function countTone(n: number | null, warnAbove = 0): 'default' | 'success' | 'danger' {
  if (n === null) return 'default';
  if (n > warnAbove) return 'danger';
  return 'success';
}

function fmtTimestamp(iso: string | null): string {
  if (!iso) return '—';
  try {
    return new Date(iso).toLocaleString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
    });
  } catch {
    return iso;
  }
}

function fmtDate(d: string | null): string {
  if (!d) return '—';
  return d;
}

// ── Widget ────────────────────────────────────────────────────────────────────

export function SecurityPostureWidget() {
  const { audit, auditLog, agentLog } = posture;

  const neverRun = audit.total === null;

  return (
    <Card padding="none" aria-label="Security posture summary">
      <Card.Header
        metadata={<Badge tone={gradeTone(auditLog.grade)}>{auditLog.grade ?? '—'}</Badge>}
      >
        <Card.Title>Security Posture</Card.Title>
        <Card.Description>Last sidecar: {fmtDate(audit.lastRunDate) ?? '—'}</Card.Description>
      </Card.Header>
      <Card.Body>
        <Stack direction="row" gap="gap" style={{ flexWrap: 'wrap' }}>
          <Card.Metric
            label="Critical"
            value={neverRun ? '—' : String(audit.critical ?? '—')}
            tone={countTone(audit.critical, 0)}
          />
          <Card.Metric
            label="High"
            value={neverRun ? '—' : String(audit.high ?? '—')}
            tone={countTone(audit.high, 0)}
          />
          <Card.Metric
            label="Moderate"
            value={neverRun ? '—' : String(audit.moderate ?? '—')}
            tone={countTone(audit.moderate, 0)}
          />
          <Card.Metric
            label="Low"
            value={neverRun ? '—' : String(audit.low ?? '—')}
            tone={countTone(audit.low, 0)}
          />
        </Stack>
      </Card.Body>
      <Card.Body>
        <div style={s.metaGrid}>
          <Field label="Last audit entry" value={fmtDate(auditLog.lastEntryDate)} />
          <Field label="Last agent run" value={fmtTimestamp(agentLog.lastTimestamp)} />
          <Field label="Unit" value={agentLog.lastUnitId ?? '—'} />
          <Field
            label="Outcome"
            value={agentLog.lastOutcome ?? '—'}
            tone={agentLog.lastOutcome === 'success' ? 'success' : 'default'}
          />
        </div>
      </Card.Body>
      {neverRun && (
        <Card.Footer>
          <p style={s.notYetRun}>
            Sidecar not generated — run <code style={s.code}>pnpm audit:sidecar</code> to populate
          </p>
        </Card.Footer>
      )}
    </Card>
  );
}

// ── Styles ────────────────────────────────────────────────────────────────────

const s = {
  widget: { display: 'flex', flexDirection: 'column', gap: hds.semantic.space.component.gap },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' },
  title: {
    ...hds.typeStyles.ui,
    margin: 0,
    color: 'var(--semantic-color-content-primary)',
  } as CSSProperties,
  subtitle: {
    ...hds.typeStyles.caption,
    margin: 0,
    color: 'var(--semantic-color-content-secondary)',
  } as CSSProperties,
  divider: { height: '1px', background: 'var(--semantic-color-border-default)' },
  metaGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))',
    gap: hds.semantic.space.component.gap,
  },
  notYetRun: {
    ...hds.typeStyles.caption,
    margin: 0,
    color: 'var(--semantic-color-content-tertiary)',
    fontStyle: 'italic',
  } as CSSProperties,
  code: { fontFamily: 'var(--font-mono, monospace)', fontSize: '11px' },
} satisfies Record<string, CSSProperties>;
